// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtESu_C_FRTMAt8Kf2kdIppa35NAViVcw',
    appId: '1:733908041215:web:e8bc7d31077d87e2d47bca',
    messagingSenderId: '733908041215',
    projectId: 'crypto-list-app-2023',
    authDomain: 'crypto-list-app-2023.firebaseapp.com',
    storageBucket: 'crypto-list-app-2023.appspot.com',
    measurementId: 'G-WP4GF1ZZ8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATN5AqFdtuR3gsBUcnTx-8sf8An9daS4w',
    appId: '1:733908041215:android:642051adffa74f84d47bca',
    messagingSenderId: '733908041215',
    projectId: 'crypto-list-app-2023',
    storageBucket: 'crypto-list-app-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKygNJXq41MG2nBRBTMpec6oRJ2-4LNg0',
    appId: '1:733908041215:ios:046e21a71655ffb1d47bca',
    messagingSenderId: '733908041215',
    projectId: 'crypto-list-app-2023',
    storageBucket: 'crypto-list-app-2023.appspot.com',
    iosClientId: '733908041215-686bfr442dvkeb89l18k3ksce8aa9ot8.apps.googleusercontent.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKygNJXq41MG2nBRBTMpec6oRJ2-4LNg0',
    appId: '1:733908041215:ios:046e21a71655ffb1d47bca',
    messagingSenderId: '733908041215',
    projectId: 'crypto-list-app-2023',
    storageBucket: 'crypto-list-app-2023.appspot.com',
    iosClientId: '733908041215-686bfr442dvkeb89l18k3ksce8aa9ot8.apps.googleusercontent.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );
}
